name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Setup Node.js 22
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          VITE_IZIPAY_PUBLIC_KEY: '${{ secrets.VITE_IZIPAY_PUBLIC_KEY }}'
      - name: Deploy to Firebase Hosting and Functions
        env:
          SERVICE_ACCOUNT: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          IZIPAY_SHOP_ID: '${{ secrets.IZIPAY_SHOP_ID }}'
          IZIPAY_TEST_PASSWORD: '${{ secrets.IZIPAY_TEST_PASSWORD }}'
          IZIPAY_HMAC_SHA256: '${{ secrets.IZIPAY_HMAC_SHA256 }}'
          VITE_IZIPAY_PUBLIC_KEY: '${{ secrets.VITE_IZIPAY_PUBLIC_KEY }}'
        run: |
          echo "$SERVICE_ACCOUNT" > sa.json
          export GOOGLE_APPLICATION_CREDENTIALS="${PWD}/sa.json"
          
          # Crear archivo .env para que la Cloud Function lea las llaves automáticamente
          echo "IZIPAY_SHOP_ID=$IZIPAY_SHOP_ID" > .env
          echo "IZIPAY_TEST_PASSWORD=$IZIPAY_TEST_PASSWORD" >> .env
          echo "IZIPAY_HMAC_SHA256=$IZIPAY_HMAC_SHA256" >> .env
          echo "VITE_IZIPAY_PUBLIC_KEY=$VITE_IZIPAY_PUBLIC_KEY" >> .env
          
          npx firebase-tools deploy --only hosting,functions --project gen-lang-client-0484978887 -f
